### ISSUE TITLE
Shorten from your CLI

### ISSUE THREAD

**Issue by eexit** [nelsontky/gh-pages-url-shortener#49]
Hey,

I created a small bash script to automate this, based on [GitHub CLI](https://github.com/cli/cli):

```bash
#!/bin/bash
[[ ! -z "$@" ]] && (gh issue create --repo eexit/s --label "cli" --title "$@" --body "" | sed -e 's/github.com\/eexit\/s\/issues/eexit.github.io\/s/g') || (echo "Forgot URL?"; exit 1)
```

![Screenshot 2020-11-17 at 11 18 35 PM](https://user-images.githubusercontent.com/57098/99458241-81ec9f00-292c-11eb-9459-b065bfc723ed.png)

Note: my repo is https://github.com/eexit/s

**Comment by nelsontky** [comment]
Thats great! You could update the README to include this information and open a PR

**Comment by nelsontky** [comment]
Great stuff! Added your fork and bash script to README!

**Comment by rasa** [comment]
Cool hack! Here are a few tweaks to consider:
```
[[ ! -z "$@" ]] &&
```
could be simplified to:
``` 
(($#)) &&
```
Also,
```
sed -e 's/github.com\/eexit\/s\/issues/eexit.github.io\/s/g'
```
could be simplified to:
```
sed -e 's|github\.com/eexit/s/issues|eexit.github.io/s|g'
```
Also [Why #!/usr/bin/env bash is superior to #!/bin/bash](https://stackoverflow.com/questions/21612980/why-is-usr-bin-env-bash-superior-to-bin-bash/21613044)

So:
```
#!/usr/bin/env bash
(($#)) && {gh issue create --repo eexit/s --label "cli" --title "$@" --body "" | sed -e 's|github\.com/eexit/s/issues|eexit.github.io/s|g'} || {echo "Forgot URL?"; exit 1}

**Comment by eexit** [comment]
Thanks for your input @rasa. I'll test this and let you know how better this works.

**Comment by chadmayfield** [comment]
@eexit & @rasa great ideas!  I've done the same thing, but I like interact with the [API directly](https://docs.github.com/en/free-pro-team@latest/rest/reference/issues#create-an-issue) directly using curl rather than installing anything else like gh.  That way I can use it anywhere curl is installed (which should be everywhere).  Hopefully this will help someone in the future looking for an alternative method;

**Assumption**:  You have created a label in GitHub issues named `url`.
```
#!/usr/bin/env bash

if [ $# -ne 1 ]; then
  echo "You must pass a URL to shorten as an argument!"
  exit 1
fi

curl -X POST \
  -u $USERNAME:$TOKEN \
  -d "{\"title\": \"$1\",\"labels\": [\"url\"],\"assignees\": [\"$USERNAME\"]}" \
  https://api.github.com/repos/$USERNAME/$REPO/issues
```

(Just replace $USERNAME, $TOKEN, & $REPO with your GitHub username, Personal Access Token, and repo name and save to a script and make it executable.)

And finally use it: `./shorten.sh https://google.com/`

P.S. @nelsontky great work on the original code!
